version: "3.9"
services:
  service_user:
    image: service_user
    ports:
      - "8888:8888"
    environment:
      - DOCUMENTDB_DATABASE_URI=mongodb://root:example@test_local_mongo_1:27017/
      - USER_SERVICE_URL = "http://service_user_service_user_1:8888/api/v1/users"
      - CONCERT_SERVICE_URL = "http://service_concert_service_concert_1:7777/api/v1/concerts"
      - TICKET_SERVICE_URL = "http://service_ticket_service_ticket_1:9999/api/v1/tickets"

networks:
  default:
    name: ticketoverflow
    external: true
