version: "3.9"
services:
  service_concert:
    image: service_ticket
    ports:
      - "7777:7777"
    environment:
      - DOCUMENTDB_DATABASE_URI=mongodb://root:example@test_local_mongo_1:27017/

networks:
  default:
    name: ticketoverflow
    external: true
